import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {DatabaseSync} from 'node:sqlite';
const agreement=JSON.parse(readFileSync(new URL('../server/agreement.json',import.meta.url)));
const source=readFileSync(new URL('../functions/submit-enrollment.js',import.meta.url),'utf8').replace("import agreement from '../server/agreement.json';",`const agreement=${JSON.stringify(agreement)};`);
const {onRequestPost}=await import('data:text/javascript;base64,'+Buffer.from(source).toString('base64'));
let ip=0, tests=0, mail=[];
function environment(){
 const sql=new DatabaseSync(':memory:');sql.exec(readFileSync(new URL('../server/schema.sql',import.meta.url),'utf8'));
 return {MS_GRAPH_CLIENT_ID:'synthetic',MS_GRAPH_CLIENT_SECRET:'synthetic',MS_GRAPH_TENANT_ID:'synthetic',ENROLLMENT_DB:{prepare(q){return {bind(...args){return {async first(){return sql.prepare(q).get(...args)},async run(){return {meta:{changes:sql.prepare(q).run(...args).changes}}}}}}}}};
}
function payload(){return {submissionId:crypto.randomUUID(),agreementVersion:agreement.version,agreementSha256:agreement.sha256,agreementText:agreement.terms.join('\n'),selectedProducts:['FordEngage'],configuration:'Synthetic test only',enrollment:{dealer_name:'SYNTHETIC TEST — not an enrollment',pa_code:'TEST',address:'123 Test St',city:'Detroit',state:'MI',zip:'48201',pc_first:'Synthetic',pc_last:'Tester',pc_title:'General Manager',pc_email:'scott.anderson@smartdealer.com'},signer:{name:'Synthetic Signer',title:'General Manager',phone:'555-555-0100',email:'scott.anderson@smartdealer.com'},consent:{checked:true,text:agreement.consent,capturedAtClient:new Date().toISOString()}};}
async function send(p,env=environment(),origin='https://fordengage.livecode.tech',sameIp){const response=await onRequestPost({env,request:new Request('https://fordengage.livecode.tech/submit-enrollment',{method:'POST',headers:{Origin:origin,'Content-Type':'application/json','CF-Connecting-IP':sameIp||`synthetic-${++ip}`},body:JSON.stringify(p)})});return {status:response.status,data:await response.json(),cache:response.headers.get('Cache-Control')};}
function mock(status=202,throws=false){mail=[];globalThis.fetch=async(url,options)=>{if(url.includes('oauth2'))return Response.json({access_token:'synthetic'});mail.push(JSON.parse(options.body));if(throws)throw new Error('synthetic disconnect');return new Response(null,{status});};}
async function test(name,fn){await fn();tests++;console.log('PASS',name);}
await test('success includes authoritative legal text, server receipt, price and exactly Scott + primary contact',async()=>{mock();const p=payload();p.pricingSummary={price:1};const r=await send(p);assert.equal(r.status,200);assert.equal(r.data.resolved_price.price,499);assert.notEqual(r.data.receipt_id,p.submissionId);assert.equal(r.data.agreementText,agreement.terms.join('\n'));assert.deepEqual(mail[0].message.toRecipients.map(x=>x.emailAddress.address),['scott@smartdealer.com','scott.anderson@smartdealer.com']);assert.equal(r.data.email_status,'queued');assert.match(r.cache,/no-store/);for(const v of ['Synthetic Signer','$499/mo',agreement.version,agreement.consent,r.data.receipt_id])assert.ok(r.data.agreement_html.includes(v));});
await test('retries and duplicate payload IDs produce one receipt and one send',async()=>{mock();const env=environment(),p=payload();const first=await send(p,env);const repeat=await send(p,env);p.submissionId=crypto.randomUUID();const duplicate=await send(p,env);assert.equal(mail.length,1);assert.equal(repeat.data.receipt_id,first.data.receipt_id);assert.equal(duplicate.data.receipt_id,first.data.receipt_id);});
await test('concurrent duplicate submissions send once',async()=>{mock();const env=environment(),p=payload();const out=await Promise.all([send(p,env),send(p,env)]);assert.equal(mail.length,1);assert.ok(out.some(r=>r.data.ok));});
await test('same ID cannot accept different entries',async()=>{mock();const env=environment(),p=payload();await send(p,env);p.signer.name='Different';assert.equal((await send(p,env)).status,409);assert.equal(mail.length,1);});
await test('same primary contact and Scott are deduplicated',async()=>{mock();const p=payload();p.enrollment.pc_email='Scott@smartdealer.com';await send(p);assert.equal(mail[0].message.toRecipients.length,1);});
await test('configured fixed recipient is respected, client recipient override ignored',async()=>{mock();const env=environment();env.ENROLLMENT_RECIPIENT='scott.anderson@smartdealer.com';const p=payload();p.recipient='attacker@example.com';await send(p,env);assert.deepEqual(mail[0].message.toRecipients,[{emailAddress:{address:'scott.anderson@smartdealer.com'}}]);});
for(const [name,mutate] of [
 ['missing consent',p=>p.consent.checked=false],['invalid primary email',p=>p.enrollment.pc_email='x'],['header injection',p=>p.enrollment.pc_email='scott@smartdealer.com\r\nBcc: x@example.com'],['multiple email addresses',p=>p.enrollment.pc_email='scott@smartdealer.com,x@example.com'],['client legal text tampering',p=>p.agreementText+='altered'],['version tampering',p=>p.agreementVersion='x'],['hash tampering',p=>p.agreementSha256='0'.repeat(64)],['duplicate product',p=>p.selectedProducts=['FordEngage','FordEngage']],['unknown product',p=>p.selectedProducts=['x']],['custom quote',p=>p.selectedProducts=['FordEngage','eStore']],['missing dealer',p=>p.enrollment.dealer_name=''],['bad phone',p=>p.signer.phone='x'],['honeypot',p=>p.website='spam'],['wrong consent text',p=>p.consent.text='yes'],['object field',p=>p.enrollment.pc_email={x:1}],['bad timestamp',p=>p.consent.capturedAtClient='nonsense']
])await test(name,async()=>{mock();const p=payload();mutate(p);const r=await send(p);assert.equal(r.data.ok,false);assert.equal(mail.length,0);});
await test('all three product price resolves correctly',async()=>{mock();const p=payload();p.selectedProducts=['eStore','VDP Widget','FordEngage'];assert.equal((await send(p)).data.resolved_price.price,899);});
await test('foreign origin denied',async()=>{mock();assert.equal((await send(payload(),environment(),'https://evil.example')).status,403);assert.equal(mail.length,0);});
await test('provider rejection never claims success or duplicates on retry',async()=>{mock(400);const env=environment(),p=payload();assert.equal((await send(p,env)).status,502);assert.equal((await send(p,env)).data.ok,false);assert.equal(mail.length,1);});
await test('ambiguous provider failure never resends or claims success',async()=>{mock(202,true);const env=environment(),p=payload();assert.equal((await send(p,env)).data.ok,false);assert.equal((await send(p,env)).status,409);assert.equal(mail.length,1);});
await test('missing storage fails closed',async()=>{mock();const env=environment();delete env.ENROLLMENT_DB;assert.equal((await send(payload(),env)).status,503);assert.equal(mail.length,0);});
await test('IP rate limit persists across distinct submissions',async()=>{mock();const env=environment();for(let i=0;i<5;i++){const p=payload();p.enrollment.dealer_name+=' '+i;await send(p,env,undefined,'same-ip');}assert.equal((await send(payload(),env,undefined,'same-ip')).status,429);assert.equal(mail.length,5);});
await test('HTML escapes user content',async()=>{mock();const p=payload();p.signer.name='<script>alert(1)</script>';const r=await send(p);assert.ok(!r.data.agreement_html.includes('<script>'));assert.ok(r.data.agreement_html.includes('&lt;script&gt;'));});
console.log(`${tests} server checks passed; no external email calls made.`);
